# Generated by Django 2.0.6 on 2018-09-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asha',
            name='number',
        ),
        migrations.AddField(
            model_name='asha',
            name='phone_number',
            field=models.CharField(default=0, max_length=13),
            preserve_default=False,
        ),
    ]
