# Generated by Django 2.0.6 on 2018-09-28 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20180928_0411'),
    ]

    operations = [
        migrations.CreateModel(
            name='child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_time', models.DateTimeField()),
                ('delivery_place', models.CharField(max_length=100)),
                ('baby_status', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('birth_weight', models.IntegerField(help_text='in kgs only')),
                ('birth_defect', models.CharField(max_length=150)),
                ('sex', models.CharField(max_length=10)),
                ('single', models.BooleanField()),
                ('mother', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.mother')),
            ],
        ),
    ]
