# Generated by Django 2.0.6 on 2018-10-05 05:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_child'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='delivery_place',
        ),
        migrations.RemoveField(
            model_name='child',
            name='delivery_time',
        ),
        migrations.RemoveField(
            model_name='child',
            name='single',
        ),
        migrations.RemoveField(
            model_name='child',
            name='type',
        ),
        migrations.AddField(
            model_name='child',
            name='comment',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='child',
            name='delivery_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mother',
            name='comment',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
