# Generated by Django 2.1.2 on 2018-10-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20181005_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='sex',
            field=models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Others')], max_length=1),
        ),
    ]
