# Generated by Django 2.1.2 on 2018-10-09 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20181009_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='chc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='district',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='phc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='village',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('chc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.chc')),
            ],
        ),
        migrations.AlterField(
            model_name='mother',
            name='chc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.chc'),
        ),
        migrations.AlterField(
            model_name='mother',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.district'),
        ),
        migrations.AlterField(
            model_name='mother',
            name='phc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.phc'),
        ),
        migrations.AlterField(
            model_name='mother',
            name='village',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.village'),
        ),
        migrations.AddField(
            model_name='phc',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.village'),
        ),
        migrations.AddField(
            model_name='chc',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.district'),
        ),
    ]
