# Generated by Django 2.1.2 on 2018-10-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20181012_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mother',
            name='asha_name',
        ),
        migrations.AddField(
            model_name='mother',
            name='asha_name',
            field=models.ManyToManyField(to='website.asha'),
        ),
    ]
