# Generated by Django 2.1.2 on 2018-10-12 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20181012_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mother',
            name='asha_name',
        ),
        migrations.AddField(
            model_name='mother',
            name='asha_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.asha'),
        ),
    ]
